### ISSUE TITLE
npm run start fail

### ISSUE THREAD

**Issue by Angelarae63** [ashleemboyer/react-firebase-blog-starter#1]
'npm run start' command fails on my debian linux system. Ran the 'git clone' command from my linux terminal and made sure nodejs and npm were installed and updated. Changed directory to react-firebase-blog-starter.git. 

react-firebase-blog-starter@0.1.0 start /home/arwhisnant/react-firebase-blog-starter
> react-scripts start

sh: 1: react-scripts: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-firebase-blog-starter@0.1.0 start: `react-scripts start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-firebase-blog-starter@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arwhisnant/.npm/_logs/2019-08-27T14_01_46_574Z-debug.log

**Comment by ashleemboyer** [comment]
Oh no! Thank you for bringing this up. I _totally_ forgot that you have to run `npm install` before doing anything else. My blog post has been updated! Please give this a try and let me know if you are still having problems here.

**Comment by Angelarae63** [comment]
Yay! Success! That worked. Thanks so much. Whoo-hoo! Also, thanks for this tutorial! That was a lot of work. It is much appreciated!
